batch:
  chunkSize: 1000

spring:
  main:
    banner-mode: false
  application:
    name: "mmi-to-fhir"

data:
  writeToFile: true
  writeFileForResource: true

fhir:
  url: "http://localhost:18080/fhir"

logging:
  level:
    de.medizininformatik_initiative: DEBUG
