DROP TABLE COMPOSITIONELEMENT IF EXISTS;
DROP TABLE ITEM IF EXISTS;
DROP TABLE ITEM_ATC IF EXISTS;
DROP TABLE ITEM_COMPOSITIONELEMENT IF EXISTS;
DROP TABLE MOLECULE IF EXISTS;
DROP TABLE PACKAGE IF EXISTS;
DROP TABLE PRODUCT IF EXISTS;
DROP TABLE CATALOGENTRY IF EXISTS;

CREATE TABLE CATALOGENTRY AS
SELECT *
FROM CSVREAD
    (
        'data/CATALOGENTRY.CSV',
        null,
        'charset=UTF-8 fieldSeparator=;'
    );

ALTER TABLE CATALOGENTRY ALTER COLUMN CATALOGID SET NOT NULL;
ALTER TABLE CATALOGENTRY ALTER COLUMN CODE SET NOT NULL;
ALTER TABLE CATALOGENTRY ADD PRIMARY KEY (CATALOGID, CODE);

CREATE TABLE MOLECULE AS
SELECT *
FROM CSVREAD
    (
        'data/MOLECULE.CSV',
        null,
        'charset=UTF-8 fieldSeparator=;'
    );

ALTER TABLE MOLECULE ALTER COLUMN ID SET NOT NULL;
ALTER TABLE MOLECULE ADD PRIMARY KEY (ID);

CREATE TABLE COMPOSITIONELEMENT AS
SELECT *
FROM CSVREAD
    (
        'data/COMPOSITIONELEMENT.CSV',
        null,
        'charset=UTF-8 fieldSeparator=;'
    );

ALTER TABLE COMPOSITIONELEMENT ALTER COLUMN ID SET NOT NULL;
ALTER TABLE COMPOSITIONELEMENT ADD PRIMARY KEY (ID);
ALTER TABLE COMPOSITIONELEMENT ADD FOREIGN KEY (MOLECULEID) REFERENCES MOLECULE(ID);

CREATE TABLE PRODUCT AS
SELECT *
FROM CSVREAD
    (
        'data/PRODUCT.CSV',
        null,
        'charset=UTF-8 fieldSeparator=;'
    );

ALTER TABLE PRODUCT ALTER COLUMN ID SET NOT NULL;
ALTER TABLE PRODUCT ADD PRIMARY KEY (ID);

CREATE TABLE ITEM AS
SELECT *
FROM CSVREAD
    (
        'data/ITEM.CSV',
        null,
        'charset=UTF-8 fieldSeparator=;'
    );

ALTER TABLE ITEM ALTER COLUMN ID SET NOT NULL;
ALTER TABLE ITEM ADD PRIMARY KEY (ID);
ALTER TABLE ITEM ADD FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(ID);

CREATE TABLE ITEM_ATC AS
SELECT *
FROM CSVREAD
    (
        'data/ITEM_ATC.CSV',
        null,
        'charset=UTF-8 fieldSeparator=;'
    );

ALTER TABLE ITEM_ATC ADD FOREIGN KEY (ITEMID) REFERENCES ITEM(ID);
ALTER TABLE ITEM_ATC ADD FOREIGN KEY (ATCCATALOGID, ATCCODE) REFERENCES CATALOGENTRY(CATALOGID, CODE);

CREATE TABLE ITEM_COMPOSITIONELEMENT AS
SELECT *
FROM CSVREAD
    (
        'data/ITEM_COMPOSITIONELEMENT.CSV',
        null,
        'charset=UTF-8 fieldSeparator=;'
    );

ALTER TABLE ITEM_COMPOSITIONELEMENT ADD FOREIGN KEY (ITEMID) REFERENCES ITEM(ID);
ALTER TABLE ITEM_COMPOSITIONELEMENT ADD FOREIGN KEY (COMPOSITIONELEMENTID) REFERENCES COMPOSITIONELEMENT(ID);

CREATE TABLE PACKAGE AS
SELECT *
FROM CSVREAD
    (
        'data/PACKAGE.CSV',
        null,
        'charset=UTF-8 fieldSeparator=;'
    );

ALTER TABLE PACKAGE ALTER COLUMN ID SET NOT NULL;
ALTER TABLE PACKAGE ADD PRIMARY KEY (ID);
ALTER TABLE PACKAGE ADD FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(ID);
